### ISSUE TITLE
This modules is throwing some errors

### ISSUE THREAD

**Issue by affibox** [mmazzarolo/react-native-beacons-android#19]
Please follow this issue on this link: https://github.com/MacKentoch/reactNativeBeaconExample/issues/1

I've try in many ways to install this lib an it only throws errors
![image](https://cloud.githubusercontent.com/assets/8114543/17600237/97c0a454-5fd0-11e6-9d86-38de8e3fe469.png)

I also try this: 
""'@affibox Alright this issues is due to RN 0.29+.
rnpm is now integrated into react native does no more have the same behaviors.

Thank you for having submitted this issue I was not aware of that before!
So since RN 0.29+:

no more use rnpm link
if too late, so follow react-native-beacons-android#issuecomment-233583330 to fix it (I tested this fix it works)
but use react-native link (you won't have to fix with that)
Now you have also an answer for react-native-beacons-android#18 so that I save a bit time to @mmazzarolo (Hi btw!)"""

An the las issue was this:
'''C:\Users\jcbar\Desktop\affibox\reactnative\RuralKing>react-native link
rnpm-link info Android module react-native-beacons-android is already linked
rnpm-link info Linking assets to ios project
rnpm-link ERR! It seems something went wrong while linking. Error: Expected "/\* Begin ", "/\* End ", "\"" or [A-Za-z0-9_.] but "<" found.
Please file an issue here: https://github.com/rnpm/rnpm/issues

C:\Users\jcbar\Desktop\affibox\reactnative\RuralKing\node_modules\promise\lib\done.js:10
throw err;
^
SyntaxError: Expected "/\* Begin ", "/\* End ", "\"" or [A-Za-z0-9_.] but "<" found.

C:\Users\jcbar\Desktop\affibox\reactnative\RuralKing>'''

**Comment by mmazzarolo** [comment]
Hello @affibox!  
Let's try to isolate the issues by creating a new react-native project (just follow the steps below):
1. I guess you installed globally the react-native cli, let's update it: `npm i -g react-native-cli`
2. Initialize a new react-native project `react-native init TestProject` (this should install a new project with the current `0.30` release)
3. Go to the new project `cd TestProject` and install the stable version of react-native-beacons-android: `npm i -S react-native-beacons-android@1.3.1`
4. Link the react-native-beacons-android module to the android internals with `react-native link`
5. Try using the module on a real device (not on an emulated one)

Let me know what happens when you follow the steps above :)
