### ISSUE TITLE
Doesn't work properly on Android 7

### ISSUE THREAD

**Issue by ipeychev** [mmazzarolo/react-native-beacons-android#29]
The module doesn't work properly on Android 7. The iBeacons are being detected and in the next second undetected, and then again detected... despite the phone stays next to the beacon. It looks like connection is being lost every a few seconds. This issue does not exist on Android 6, it started to happen once the phone was upgraded to Android 7.

**Comment by mmazzarolo** [comment]
I'll be honest with you, this is still an open issue I recently discovered and it is caused by [the altBeacon library](https://github.com/AltBeacon/android-beacon-library/issues?utf8=%E2%9C%93&q=android%207).  
I already tried updating the AltBeacon library version (> 2.6) in the [build gradle](https://github.com/mmazzarolo/react-native-beacons-android/blob/master/android/build.gradle) and it broke the beacon scanning without showing any error output. 
... and I'm very busy at work this days and can't investigate further, so any external help is appreciated!

**Comment by felixaa** [comment]
Tried updating AltBeacon to 2.9.1. Unfortunately It wont detect the beacons at all now...

**Comment by felixaa** [comment]
In Android N they seem to have changed up the BLE scanning behaviour

> We’ve changed the BLE Scanning behavior starting in DP4. We’ll prevent applications from starting and stopping scans more than 5 times in 30 seconds. For long running scans, we’ll convert them into opportunistic scans.

If you change the scanperiod to 6000 ms it should consistently show the beacons

**Comment by ardalann** [comment]
Fixed this issue and submitted a PR ( #34 ).
